# fly.toml app configuration file generated for flux-cost-bot-solitary-shadow-2037 on 2025-11-01T08:39:08-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flux-cost-bot-solitary-shadow-2037'
primary_region = 'gru'

[build]

# Define el proceso principal de la aplicación.
# Para un worker, no necesitamos exponer puertos.
[processes]
  app = "python main.py"

# Define el tamaño de la máquina virtual.
# 'shared-cpu-1x' con 256MB de RAM es el tamaño más pequeño y está
# cubierto por el plan gratuito.
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
